### ISSUE TITLE
Image in preview not updating

### ISSUE THREAD

**Issue by haideralipunjabi** [ajayns/previewer#3]
I am not sure whether this is a problem in the code or in my browser.

If I try to open an image which has not completely finished loading yet(in the thumbnail), and an image has been previously opened in the previewer(doesn't matter if the image was loaded or not), the old image opens in the previewer (will continue loading if it hasn't been completely loaded yet). 

I inspected it, and the src attribute is updating but the image itself isn't.

I can submit a fix as PR if you can verify that this is a bug in the code, and not in my browser. :smiley:

**Comment by ajayns** [comment]
I'll be looking into this matter soon, give me a few hours!

**Comment by ajayns** [comment]
I don't seem to be noticing this issue in my browser. Do attach screenshots and tell me what would you like to make as a fix?

**Comment by haideralipunjabi** [comment]
Check the uploaded gif.

I recommend adding `$("#previewer-img").attr("src", '');` to the closeWindow function to solve it. :smile: 
![ezgif-1-d0f2a0c4f5](https://user-images.githubusercontent.com/11888687/27900731-21c6d072-624d-11e7-8f5e-c351f47b3c3c.gif)

**Comment by ajayns** [comment]
Oh yes, I've been thinking the same but never thought any issue would arise out of it. Currently, I've changed the code to vanillaJS and so will be adding a fix for this right away. @haideralipunjabi 
Thanks for noting this issue

**Comment by ajayns** [comment]
I've made the changes with the last commit. I believe this issue is resolved with that!
